default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: luisferrassini
  password: example
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: luisferrassini_development

test:
  <<: *default
  database: luisferrassini_test